lib/livrodealemao_web/router.ex
defmodule LivrodealemaoWeb.Router do
  use LivrodealemaoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LivrodealemaoWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/contato", ContatoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", LivrodealemaoWeb do
  #   pipe_through :api
  # end
end

lib/livrodealemao/application.ex
defmodule Livrodealemao.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Livrodealemao.Repo,
      # Start the endpoint when the application starts
      LivrodealemaoWeb.Endpoint
      # Starts a worker by calling: Livrodealemao.Worker.start_link(arg)
      # {Livrodealemao.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Livrodealemao.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    LivrodealemaoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/livrodealemao/contact.ex
defmodule Livrodealemao.Contact do
  use Ecto.Schema
  import Ecto.Changeset
  alias Livrodealemao.Contact

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "contacts" do
    field :email, :string
    field :mensagem, :string
    field :nome, :string

    timestamps()
  end

  @doc false
  def changeset(%Contact{}=contact, attrs \\ %{}) do
    contact
    |> cast(attrs, [:nome, :email, :mensagem])
    |> validate_required([:nome, :email, :mensagem])
    |> validate_format(:email, ~r/@/)
  end
end

lib/livrodealemao/repo.ex
defmodule Livrodealemao.Repo do
  use Ecto.Repo,
    otp_app: :livrodealemao,
    adapter: Ecto.Adapters.Postgres
end

lib/livrodealemao_web/controllers/contato_controller.ex
defmodule LivrodealemaoWeb.ContatoController do
  use LivrodealemaoWeb, :controller
  alias Livrodealemao.Contact
  alias Livrodealemao.Repo

  def new(conn, _params) do
  	changeset = Contact.changeset(%Contact{})
  	render(conn, "contato.html", changeset: changeset)
  end

  def create(conn, %{"contact" => contact_params}) do
  changeset = Contact.changeset(%Contact{}, contact_params)
  case Repo.insert(changeset) do
    {:ok, _contact} ->
      conn
      |> put_flash(:info, "Obrigado pela sua mensagem!")
      |> redirect(to: "/")
    {:error, changeset} ->
      render(conn, "contato.html", changeset: changeset)
  end
end
  
end

lib/livrodealemao_web/controllers/page_controller.ex
defmodule LivrodealemaoWeb.PageController do
  use LivrodealemaoWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def contato(conn, _params) do
  	render(conn, "contato.html")
  end
  
end

lib/livrodealemao_web/views/contato_view.ex
defmodule LivrodealemaoWeb.ContatoView do
  use LivrodealemaoWeb, :view
end

lib/livrodealemao_web/views/error_view.ex
defmodule LivrodealemaoWeb.ErrorView do
  use LivrodealemaoWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/livrodealemao_web/views/layout_view.ex
defmodule LivrodealemaoWeb.LayoutView do
  use LivrodealemaoWeb, :view
end

lib/livrodealemao_web/views/page_view.ex
defmodule LivrodealemaoWeb.PageView do
  use LivrodealemaoWeb, :view
end

lib/livrodealemao_web/templates/contato/contato.html.eex
<h1>Vamos conversar? Manda uma mensagem pra gente!</h1>
  <%= form_for @changeset, Routes.contato_path(@conn, :create), fn f ->%>
    <div class="input_wrapper center_block">
      <label>Seu nome</label>
      <%= text_input f, :nome %>
    </div>

    <div class="input_wrapper center_block">
      <label>Seu email</label>
      <%= email_input f, :email %>
    </div>

    <div class="input_wrapper center_block">
      <label>Sua mensagem pra gente</label>
      <%= textarea f, :mensagem %>
    </div>

    <div class="input_wrapper center_block">
      <%= submit "Enviar" %>
    </div>
  <% end %>

lib/livrodealemao_web/templates/contato/novo.html.eex
<form>
  <div class="input_wrapper center_block">
    <label>Seu nome</label>
    <input type="text" name="nome_usuario" maxlength="250" required></input>
  </div>

  <div class="input_wrapper center_block">
    <label>Seu email</label>
    <input type="email" name="email_usuario" maxlength="250" required></input>
  </div>

  <div class="input_wrapper center_block">
    <label>Sua mensagem pra gente</label>
    <input type="textarea" name="mensagem_usuario" required></input>
  </div>

  <div class="input_wrapper center_block">
    <input type="submit" value="Enviar" class="button"></div>
  </div>
</form>

lib/livrodealemao_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="theme-color" content="#ffffff">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="36x36" href="/android-icon-36x36.png">
    <link rel="icon" type="image/png" sizes="48x48" href="/android-icon-48x48.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="144x144" href="/android-icon-144x144.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="manifest" href="/manifest.json">
    <title>Livro de Alemão</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/livrodealemao_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed and maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>